### ISSUE TITLE
Decide on language for core implementation

### ISSUE THREAD

**Issue by goverfl0w** [goverfl0w/telemetry#1]
telemetry's goals are aligned with making data structures efficient. However, it is also worth noting that a modern programming language should also try to closely follow these values as well:

- Highly performant.
- Safe on compile and runtime.
- Memory-efficient.

Because of this, we have a list of programming languages that I (personally believe) see being best for writing telemetry in:

1. C. Most languages are C-based and will run either as fast as, or similar to C which compiles directly into machine code.
2. Rust. Rust's very beneficial for its emphasis on being safe to run, and it has a very satisfying paradigm.
3. C++. It's obviously a superset of C but with the inclusion of the object orientation paradigm and better garbage collecting.

The 3rd choice may be the best. Writing the language in C would require us to manually garbage collect on our own accord which is both a gift and a curse when we begin to scale upwards to higher levels of complexity. Rust is... well, satisfying when *you get it to work.*

**Comment by arHSM** [comment]
Rust

**Comment by goverfl0w** [comment]
After some thought, I'm between C and C++ now. C allows for great benefits with being a backend for programming languages, and while I could use C++ or Rust for bootstrapping purposes, I want one language for all of my services.

C++ would give me these benefits:

- I won't be bawling my eyes out every 5 minutes fighting errors in languages foreign to me.
- C++ allows for object orientation. Rust and C are not OOL in construct, and by this I mean offer a builtin implementation for things such as traits, classes and etc.
- I know C++ better than the other two.
- C++ offers us better garbage collection, at the mercy of having to fiddle with memory alloc during runtime process.

**Comment by Sprocket06** [comment]
Rust will provide a much higher level of support and utility, but offers a correspondingly much higher learning curve as much of the language-provided documentation assumes you already know what you're looking for. 
C++ is likely going to give you better support than C, but will require you to write pretty much every utility function you may need yourself.

**Comment by Jonitrexis** [comment]
+1 for Rust.

**Comment by jean1398reborn** [comment]
+1 for Rust.

**Comment by goverfl0w** [comment]
Discussed in our server, I will be removing Rust as a choice for the reasons given above towards preference. The learning curve is also extremely sharp for something I'm not quite comfortable with using just yet, so I'd like to be with a language I'm more familiarized with overall.

Developing a language should not require me to learn one at the same time.

**Comment by goverfl0w** [comment]
Closing this Issue. We've determined our language set as C and C++ for core services and bootstrapping.
